-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : mer. 11 déc. 2024 à 13:59
-- Version du serveur : 10.4.27-MariaDB
-- Version de PHP : 8.1.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `plantify`
--

-- --------------------------------------------------------

--
-- Structure de la table `plants`
--

CREATE TABLE `plants` (
  `id` varchar(10) NOT NULL,
  `name` varchar(255) NOT NULL,
  `scientific_name` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `sunshine` varchar(100) DEFAULT NULL,
  `difficulty` varchar(50) DEFAULT NULL,
  `image_url` text DEFAULT NULL,
  `position` point DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `characteristics` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`characteristics`)),
  `traditional_uses` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`traditional_uses`)),
  `cultural_significance` text DEFAULT NULL,
  `well_being` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`well_being`)),
  `fun_fact` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `plants`
--

INSERT INTO `plants` (`id`, `name`, `scientific_name`, `description`, `sunshine`, `difficulty`, `image_url`, `position`, `location`, `characteristics`, `traditional_uses`, `cultural_significance`, `well_being`, `fun_fact`) VALUES
('1', 'Rose', 'Rosa × odorata', 'La rose est une fleur élégante et parfumée, symbole de l\'amour et de la passion. Ses pétales délicats et son parfum envoûtant en font l\'une des fleurs les plus appréciées au monde.', 'Plein soleil', 'Modérée', 'https://images.pexels.com/photos/56866/garden-rose-red-pink-56866.jpeg', 0x00000000010100000076e09c11a56d4840a835cd3b4ed10240, 'Jardin des Tuileries', '{\"minerals\": [\"Fer\", \"Calcium\", \"Magnésium\"], \"vitamins\": [\"Vitamine C\"], \"antioxidants\": [\"Polyphénols\", \"Flavonoïdes\"], \"fragranceEffect\": \"Apaisante et relaxante\", \"therapeuticUses\": [\"Aide à réduire le stress\", \"Améliore la qualité du sommeil\", \"Calme les irritations cutanées\"]}', '{\"tea\": \"Les pétales de rose sont utilisés pour préparer des thés apaisants et aromatiques.\", \"essentialOil\": \"L\'huile essentielle de rose est prisée en aromathérapie pour ses propriétés relaxantes.\", \"cosmetic\": \"Les extraits de rose sont utilisés dans des produits de soins pour la peau pour leurs propriétés hydratantes et anti-âge.\"}', 'Symbole de l\'amour et de la beauté dans de nombreuses cultures à travers le monde.', '{\"stressRelief\": \"Son parfum réduit les niveaux de stress et favorise une sensation de calme.\", \"moodEnhancer\": \"Améliore l\'humeur et stimule les émotions positives.\", \"skinCare\": \"Aide à apaiser et hydrater la peau sensible.\"}', 'Les roses sont cultivées depuis plus de 5 000 ans et étaient déjà appréciées dans les jardins de la Chine antique.'),
('10', 'Lys', 'Lilium', 'Avec ses grandes fleurs parfumées, le lys incarne l\'élégance et la pureté. Il est parfait pour décorer les jardins et les intérieurs.', 'Mi-ombre', 'Modérée', 'https://media.istockphoto.com/id/105813631/fr/photo/lys-blanc-dans-un-jardin.jpg?s=612x612&w=0&k=20&c=Vcp397EmXefWLiG1wp43KWFbgTTIwpGPf21BL-XCimY=', 0x000000000101000000c3f5285c8f424440295c8fc2f5284040, 'Parc Monceau', '{\"minerals\":[],\"vitamins\":[],\"antioxidants\":[],\"therapeuticUses\":[\"Améliore l\'humeur grâce à son parfum doux\"],\"fragranceEffect\":\"Élégant et floral\"}', '{\"religious\":\"Utilisé comme symbole de pureté dans l\'art et la religion.\",\"gifts\":\"Souvent offert lors de mariages ou d\'événements religieux.\",\"gardens\":\"Apporte une touche majestueuse aux espaces extérieurs.\"}', 'Symbole de la royauté dans l\'héraldique française.', '{\"moodEnhancement\":\"Son parfum stimule les émotions positives.\",\"decor\":\"Évoque un sentiment de sérénité et de luxe.\",\"tradition\":\"Reflète des valeurs de noblesse et de pureté.\"}', 'Le lys blanc est souvent associé à la Vierge Marie dans la tradition chrétienne.'),
('11', 'Hortensia', 'Hydrangea', 'L\'hortensia est un arbuste florissant dont les couleurs varient selon le pH du sol, allant du bleu au rose.', 'Mi-ombre', 'Modérée', 'https://img.freepik.com/photos-premium/fleurs-hortensia-bleu-bouchent_196038-693.jpg', 0x0000000001010000001f85eb51b8464440b81e85eb51084040, 'Parc André Citroën', '{\"minerals\":[\"Aluminium (selon le sol)\"],\"vitamins\":[],\"antioxidants\":[],\"therapeuticUses\":[\"Apaisant pour les yeux grâce à ses couleurs douces\"],\"fragranceEffect\":\"Léger et subtil\"}', '{\"landscaping\":\"Idéal pour créer des massifs colorés.\",\"cutFlowers\":\"Utilisé dans les bouquets pour sa longévité.\",\"gardens\":\"Favorise un charme rustique ou sophistiqué.\"}', 'Considéré comme un symbole de gratitude et de beauté.', '{\"aesthetics\":\"Crée une atmosphère apaisante.\",\"seasonal\":\"Offre un spectacle changeant selon les saisons.\",\"decoration\":\"Parfait pour les arrangements floraux durables.\"}', 'La couleur des hortensias peut être modifiée en ajustant le pH du sol.'),
('12', 'Purple Dome', 'Aster novae-angliae', 'Le Purple Dome est une variété d\'aster compact et robuste, particulièrement apprécié pour sa floraison abondante de couleur violette intense qui illumine les jardins en fin de saison.', 'Plein soleil', 'Facile', 'https://gardengoodsdirect.com/cdn/shop/files/aster-woods-purple-29777631739946_grande.jpg?v=1695417540', 0x000000000101000000e17a14ae47464440295c8fc2f5282940, 'Jardin des Plantes, Paris', '{\"minerals\":[\"Fer\",\"Calcium\"],\"vitamins\":[],\"antioxidants\":[\"Flavonoïdes\"],\"therapeuticUses\":[\"Attire les pollinisateurs\",\"Améliore la biodiversité du jardin\"],\"fragranceEffect\":\"Délicat et herbacé\"}', '{\"gardens\":\"Excellent pour les massifs et bordures automnales\",\"bouquets\":\"Apprécié en fleurs coupées pour sa longue tenue\",\"pollinator\":\"Attire les papillons et les abeilles\"}', 'Symbolise l\'élégance et la persévérance dans le langage des fleurs', '{\"gardenHealth\":\"Contribue à la biodiversité du jardin\",\"aesthetics\":\"Apporte une touche de couleur vibrante en fin de saison\",\"wildlife\":\"Soutient la faune locale, notamment les pollinisateurs\"}', 'Contrairement à beaucoup d\'autres asters, le Purple Dome reste compact et n\'a pas besoin d\'être tuteuré'),
('13', 'Jonquille', 'Narcissus jonquilla', 'La jonquille est l\'un des premiers messagers du printemps, avec ses fleurs jaunes éclatantes et parfumées qui émergent dès la fin de l\'hiver.', 'Plein soleil à mi-ombre', 'Facile', 'https://media.istockphoto.com/id/1176574947/fr/photo/fleurs-jaunes-de-jonquille.jpg?s=612x612&w=0&k=20&c=ADY7FnrCfo7mhjD2uKL_DpHkvIhQgtxmt3YselQitQw=', 0x0000000001010000001f85eb51b8464440b81e85eb51084040, 'Parc de Bagatelle, Paris', '{\"minerals\":[\"Calcium\",\"Potassium\"],\"vitamins\":[],\"antioxidants\":[],\"therapeuticUses\":[\"Symbole du renouveau printanier\"],\"fragranceEffect\":\"Doux et printanier\"}', '{\"celebrations\":\"Symbole traditionnel du printemps et du renouveau\",\"gardens\":\"Excellente pour la naturalisation dans les pelouses\",\"cutFlowers\":\"Populaire en bouquets printaniers\"}', 'Représente l\'espoir et le renouveau dans de nombreuses cultures', '{\"moodBoost\":\"Les couleurs vives stimulent l\'optimisme\",\"seasonalMarker\":\"Annonce l\'arrivée du printemps\",\"fragrance\":\"Son parfum délicat évoque la fraîcheur printanière\"}', 'Les bulbes de jonquilles contiennent des substances toxiques qui les protègent naturellement des rongeurs'),
('14', 'Jacinthe', 'Hyacinthus orientalis', 'La jacinthe est une plante bulbeuse réputée pour ses fleurs parfumées en forme de grappe et sa palette de couleurs variées.', 'Plein soleil à mi-ombre', 'Modérée', 'https://images.ctfassets.net/b85ozb2q358o/95dd345e42affef5d6f6387dcde452fb1be0f9a51863a3fa605a023940ea62b9/9746b55f9623bf93850dffe214848276/quand-comment-planter-bulbes-fleurs-4.jpg', 0x0000000001010000001f85eb51b8464440b81e85eb51084040, 'Jardin du Luxembourg, Paris', '{\"minerals\":[\"Phosphore\",\"Potassium\"],\"vitamins\":[],\"antioxidants\":[],\"therapeuticUses\":[\"Aromathérapie naturelle\",\"Améliore l\'ambiance\"],\"fragranceEffect\":\"Intense et suave\"}', '{\"indoor\":\"Populaire pour le forçage en intérieur\",\"gardens\":\"Création de bordures parfumées\",\"aromatherapy\":\"Utilisée pour son parfum apaisant\"}', 'Symbole du printemps et de la renaissance dans la mythologie grecque', '{\"aromatherapy\":\"Le parfum aide à la relaxation\",\"seasonal\":\"Apporte de la joie pendant la période hivernale\",\"decoration\":\"Embellit les espaces intérieurs et extérieurs\"}', 'La jacinthe peut être forcée à fleurir en hiver sur un simple vase d\'eau'),
('15', 'Jasmin jaune', 'Jasminum nudiflorum', 'Le jasmin d\'hiver est un arbuste grimpant qui fleurit en plein hiver, apportant une touche de couleur dorée quand la plupart des plantes sont en dormance.', 'Plein soleil à mi-ombre', 'Facile', 'https://resize.elle.fr/article/var/plain_site/storage/images/deco/exterieur/jardin/le-jasmin-d-hiver-couleur-et-parfum-en-hiver-4191280/101392595-1-fre-FR/Le-jasmin-d-hiver-couleur-et-parfum-en-hiver.jpg', 0x0000000001010000001f85eb51b8464440b81e85eb51084040, 'Parc Monceau, Paris', '{\"minerals\":[\"Fer\",\"Magnésium\"],\"vitamins\":[],\"antioxidants\":[],\"therapeuticUses\":[\"Égaye l\'ambiance hivernale\"],\"fragranceEffect\":\"Subtil et doux\"}', '{\"landscaping\":\"Excellent pour couvrir les murs et treillages\",\"winterGarden\":\"Apporte de la couleur en hiver\",\"decoration\":\"Utilisé pour les décorations hivernales\"}', 'Symbole de joie et d\'optimisme en période hivernale', '{\"winterCheer\":\"Combat la morosité hivernale\",\"gardenInterest\":\"Maintient la vie au jardin en hiver\",\"aesthetics\":\"Crée des points focaux dorés dans le jardin\"}', 'Cette plante peut fleurir même sous la neige, d\'où son surnom de \"soleil d\'hiver\"'),
('16', 'Bruyère', 'Erica', 'La bruyère est une plante rustique qui offre des fleurs colorées pendant l\'hiver, idéale pour les jardins de rocaille et les massifs.', 'Plein soleil à mi-ombre', 'Modérée', 'https://blog.rouepepinieres.com/hs-fs/hubfs/Erica-Eva-gold-bruy%C3%A8re-couvre-sol.jpg?width=1000&height=667&name=Erica-Eva-gold-bruy%C3%A8re-couvre-sol.jpg', 0x0000000001010000001f85eb51b8464440b81e85eb51084040, 'Jardin des Serres d\'Auteuil, Paris', '{\"minerals\":[\"Fer\",\"Calcium\"],\"vitamins\":[],\"antioxidants\":[],\"therapeuticUses\":[\"Décorative et couvre-sol\"],\"fragranceEffect\":\"Léger et boisé\"}', '{\"groundcover\":\"Excellent couvre-sol pour zones acides\",\"winterColor\":\"Apporte de la couleur en hiver\",\"landscaping\":\"Idéal pour les jardins de rocaille\"}', 'Symbolise la solitude et la protection dans le folklore écossais', '{\"lowMaintenance\":\"Facile à entretenir une fois établie\",\"yearRound\":\"Procure un intérêt visuel toute l\'année\",\"wildlife\":\"Attire les abeilles et les papillons\"}', 'La bruyère peut survivre dans des conditions extrêmes et pousse naturellement sur les landes et les sols pauvres'),
('2', 'Aloe Vera', 'Aloe barbadensis miller', 'L\'Aloe Vera est une plante succulente prisée pour ses propriétés médicinales et cosmétiques. Sa sève gélatineuse est utilisée depuis des siècles pour apaiser et soigner divers maux.', 'Lumière indirecte ou soleil doux', 'Facile', 'https://img.freepik.com/premium-photo/aloe-vera-leaf-hd-stock-photographic-image-with-drops-water-gel-herbal-medecine_820616-1419.jpg', 0x000000000101000000b01bbb44f37a4140da37f08672d35dc0, 'Jardin botanique de Los Angeles', '{\"minerals\":[\"Calcium\",\"Potassium\",\"Sodium\"],\"vitamins\":[\"Vitamine A\",\"Vitamine C\",\"Vitamine E\"],\"antioxidants\":[\"Anthraquinones\"],\"therapeuticUses\":[\"Hydrate et apaise la peau\",\"Favorise la digestion\",\"Stimule la cicatrisation\"],\"fragranceEffect\":\"Légèrement purifiant et frais\"}', '{\"gel\":\"Utilisé pour apaiser les coups de soleil, les brûlures légères et les irritations cutanées.\",\"juice\":\"Consommé pour favoriser une digestion saine.\",\"cosmetic\":\"Ingrédient populaire dans les produits pour la peau et les cheveux.\"}', 'Utilisé dans la médecine traditionnelle égyptienne comme \"plante de l\'immortalité\".', '{\"skinCare\":\"Aide à réduire les inflammations et hydrate intensément.\",\"digestion\":\"Améliore la santé intestinale grâce à ses enzymes naturelles.\",\"detox\":\"Contribue à éliminer les toxines du corps.\"}', 'L\'Aloe Vera est capable de survivre plusieurs semaines sans eau grâce à sa capacité à stocker l\'humidité dans ses feuilles.'),
('3', 'Lavande', 'Lavandula angustifolia', 'La lavande est une plante aromatique emblématique des régions méditerranéennes, connue pour son parfum relaxant et ses nombreuses vertus thérapeutiques.', 'Plein soleil', 'Facile', 'https://www.creativefabrica.com/wp-content/uploads/2022/12/16/Lavender-Photography-HDR-HD-8K-4K-1080p-Sharp-Focus-55mm-52729637-1.png', 0x000000000101000000e17a14ae474644408fc2f5285c0f1640, 'Plateau de Valensole, France', '{\"minerals\":[\"Fer\",\"Magnésium\"],\"vitamins\":[\"Vitamine C\"],\"antioxidants\":[\"Linalool\",\"Linalyl acétate\"],\"therapeuticUses\":[\"Réduit le stress\",\"Améliore le sommeil\",\"Apaise les maux de tête\"],\"fragranceEffect\":\"Relaxant et équilibrant\"}', '{\"tea\":\"Préparée pour apaiser l\'esprit et favoriser un sommeil réparateur.\",\"essentialOil\":\"Utilisée en aromathérapie pour soulager l\'anxiété et la tension.\",\"sachets\":\"Placée dans les armoires pour parfumer et éloigner les insectes.\"}', 'Symbole de pureté et de calme dans les cultures méditerranéennes.', '{\"stressRelief\":\"Son arôme aide à réduire l\'anxiété et à calmer l\'esprit.\",\"sleepAid\":\"Favorise un sommeil profond et réparateur.\",\"insectRepellent\":\"Naturellement efficace contre les moustiques et autres nuisibles.\"}', 'Les Romains utilisaient la lavande pour parfumer leurs bains publics et leurs vêtements.'),
('4', 'Menthe', 'Mentha spicata', 'La menthe est une plante vivace appréciée pour sa fraîcheur et son arôme revigorant. Elle est largement utilisée en cuisine et en médecine traditionnelle.', 'Mi-ombre', 'Facile', 'https://www.shutterstock.com/shutterstock/videos/3445557255/thumb/1.jpg', 0x000000000101000000a8c64b37894544400ad7a3703d8a2940, 'Villa d\'Este, Rome', '{\"minerals\":[\"Potassium\",\"Fer\"],\"vitamins\":[\"Vitamine A\",\"Vitamine C\"],\"antioxidants\":[\"Menthol\",\"Rosmarinic acid\"],\"therapeuticUses\":[\"Favorise la digestion\",\"Apaise les douleurs musculaires\",\"Combat les nausées\"],\"fragranceEffect\":\"Revitalisant et purifiant\"}', '{\"tea\":\"Infusion populaire pour calmer l\'estomac et rafraîchir l\'haleine.\",\"oil\":\"Utilisée pour apaiser les douleurs musculaires et les maux de tête.\",\"culinary\":\"Ajoutée aux plats et boissons pour une touche de fraîcheur.\"}', 'Associée à l\'hospitalité dans de nombreuses cultures.', '{\"digestion\":\"Réduit les ballonnements et favorise la santé intestinale.\",\"freshness\":\"Rafraîchit l\'esprit et stimule la concentration.\",\"painRelief\":\"Efficace contre les douleurs légères grâce à ses propriétés analgésiques.\"}', 'La menthe est une plante si robuste qu\'elle peut envahir tout un jardin si elle n\'est pas contenue.'),
('5', 'Camomille', 'Matricaria chamomilla', 'La camomille est une plante douce et apaisante, souvent utilisée en infusion pour ses propriétés relaxantes et digestives.', 'Plein soleil', 'Facile', 'https://img.freepik.com/photos-premium/macro-champ-camomille_97070-864.jpg', 0x000000000101000000e17a14ae47464440295c8fc2f5282940, 'Berlin Botanical Gardens', '{\"minerals\":[\"Phosphore\",\"Potassium\"],\"vitamins\":[\"Vitamine A\"],\"antioxidants\":[\"Apigénine\",\"Flavonoïdes\"],\"therapeuticUses\":[\"Soulage les insomnies\",\"Calme les inflammations\",\"Aide à la digestion\"],\"fragranceEffect\":\"Apaisant et légèrement sucré\"}', '{\"tea\":\"Infusion classique pour se détendre et favoriser le sommeil.\",\"skin\":\"Préparée en lotion pour apaiser les irritations cutanées.\",\"aromatherapy\":\"Utilisée pour réduire l\'anxiété et favoriser un sentiment de bien-être.\"}', 'Connue comme \"la médecine des plantes\" dans les traditions européennes.', '{\"relaxation\":\"Favorise un état de calme et réduit l\'anxiété.\",\"digestion\":\"Apaise les troubles gastriques légers.\",\"skinCare\":\"Réduit les rougeurs et calme les inflammations.\"}', 'Les anciens Égyptiens considéraient la camomille comme sacrée et l\'offraient à leurs dieux.'),
('6', 'Fougère', 'Polypodiopsida', 'La fougère est une plante luxuriante qui évoque une ambiance tropicale. Ses frondes délicates apportent une touche de fraîcheur et d\'élégance dans les espaces ombragés.', 'Ombre ou lumière indirecte', 'Modérée', 'https://media.istockphoto.com/id/655052762/fr/photo/vert-foug%C3%A8re.jpg?s=612x612&w=0&k=20&c=OWUCTCq4x639Kgb6DsALpncGulRPB3DgFmBf7zMPGlg=', 0x000000000101000000ee7c3f355e474440c3f5285c8f024040, 'Parc Montsouris', '{\"minerals\":[\"Magnésium\",\"Fer\"],\"vitamins\":[],\"antioxidants\":[],\"therapeuticUses\":[\"Purifie l\'air ambiant\",\"Favorise l\'humidité dans l\'espace\"],\"fragranceEffect\":\"Effet naturel et apaisant\"}', '{\"indoor\":\"Utilisée pour décorer les intérieurs grâce à son feuillage dense.\",\"gardens\":\"Idéale pour les rocailles ombragées.\",\"airPurification\":\"Connue pour améliorer la qualité de l\'air.\"}', 'Symbolise la résilience et la vitalité dans plusieurs cultures.', '{\"airQuality\":\"Aide à purifier l\'air et à réduire les toxines.\",\"stressRelief\":\"Apporte une ambiance sereine et apaisante.\",\"decor\":\"Crée un environnement harmonieux et naturel.\"}', 'Les fougères existent depuis plus de 360 millions d\'années et précèdent les plantes à fleurs !'),
('7', 'Orchidée', 'Orchidaceae', 'L\'orchidée est une fleur exotique et élégante, très appréciée pour ses couleurs vibrantes et sa beauté unique. Elle symbolise la beauté et l\'élégance.', 'Lumière indirecte', 'Difficile', 'https://cdn.pixabay.com/photo/2023/02/04/21/32/flowers-7768218_640.jpg', 0x0000000001010000001f85eb51b8464440b81e85eb51084040, 'Jardin des Serres d\'Auteuil', '{\"minerals\":[\"Calcium\",\"Magnésium\"],\"vitamins\":[\"Vitamine C\"],\"antioxidants\":[\"Polyphénols\",\"Flavonoïdes\"],\"fragranceEffect\":\"Soutien émotionnel et apaisant\",\"therapeuticUses\":[\"Aide à améliorer la concentration\",\"Soulage la fatigue mentale\",\"Stimule les capacités cognitives\"]}', '{\"tea\":\"Certaines espèces d\'orchidées sont utilisées dans des tisanes pour leurs propriétés énergisantes.\",\"essentialOil\":\"L\'huile essentielle d\'orchidée est utilisée pour ses propriétés relaxantes et régénératrices.\",\"cosmetic\":\"L\'extrait d\'orchidée est utilisé dans des produits de soin pour ses propriétés hydratantes et anti-âge.\"}', 'L\'orchidée est un symbole de beauté, de sophistication et de luxe dans de nombreuses cultures.', '{\"stressRelief\":\"Sa fragrance subtile aide à réduire les niveaux de stress et favorise la relaxation.\",\"moodEnhancer\":\"Stimule la créativité et améliore l\'humeur générale.\",\"skinCare\":\"Les extraits d\'orchidée nourrissent et rajeunissent la peau, en la laissant douce et éclatante.\"}', 'Les orchidées peuvent vivre plusieurs années et certaines espèces sont connues pour leur capacité à se multiplier facilement dans les conditions appropriées.'),
('8', 'Bambou', 'Bambusoideae', 'Le bambou est une plante robuste et élégante, idéale pour créer des haies ou décorer les jardins zen. Sa croissance rapide en fait une plante unique.', 'Mi-ombre', 'Modérée', 'https://png.pngtree.com/background/20230513/original/pngtree-close-up-shot-of-a-bamboo-forest-picture-image_2507777.jpg', 0x000000000101000000c3f5285c8f424440295c8fc2f5284040, 'Parc des Buttes-Chaumont', '{\"minerals\":[\"Silice\",\"Calcium\"],\"vitamins\":[],\"antioxidants\":[],\"therapeuticUses\":[\"Atténue les tensions grâce à son ambiance relaxante\"],\"fragranceEffect\":\"Zen et rafraîchissant\"}', '{\"construction\":\"Utilisé pour construire des structures légères et durables.\",\"decor\":\"Apporte une touche asiatique et naturelle aux jardins.\",\"erosionControl\":\"Protège le sol de l\'érosion grâce à ses racines denses.\"}', 'Considéré comme un symbole de longévité et de force en Asie.', '{\"relaxation\":\"Crée un environnement paisible pour la méditation.\",\"ecoFriendly\":\"Contribue à une culture durable grâce à sa croissance rapide.\",\"aesthetics\":\"Idéal pour les espaces extérieurs zen ou modernes.\"}', 'Certaines variétés de bambou peuvent pousser jusqu\'à un mètre par jour.'),
('9', 'Tulipe', 'Tulipa', 'Symbole du printemps, la tulipe est une fleur éclatante aux multiples couleurs qui égaye les jardins avec sa beauté intemporelle.', 'Plein soleil', 'Modérée', 'https://png.pngtree.com/thumb_back/fh260/background/20230724/pngtree-tv-wallpaper-pink-tulips-wallpapers-image_10176785.jpg', 0x000000000101000000c3f5285c8f424440295c8fc2f5283f40, 'Champ de Mars', '{\"minerals\":[],\"vitamins\":[],\"antioxidants\":[],\"therapeuticUses\":[\"Apporte une sensation de joie et de renouveau\"],\"fragranceEffect\":\"Subtil et printanier\"}', '{\"bouquets\":\"Très prisée pour les arrangements floraux.\",\"celebrations\":\"Offerte en symbole d\'amour ou d\'amitié.\",\"festivals\":\"Fleur emblématique de nombreux festivals printaniers.\"}', 'Appréciée pour son rôle central dans la \"tulipomanie\" du XVIIe siècle.', '{\"moodBoost\":\"Élève l\'humeur avec ses couleurs vives.\",\"decoration\":\"Idéale pour orner jardins et intérieurs.\",\"natureConnection\":\"Favorise un lien avec la nature au printemps.\"}', 'La tulipe est originaire de Turquie et a été importée en Europe au XVIe siècle.');

-- --------------------------------------------------------

--
-- Structure de la table `plant_carousel`
--

CREATE TABLE `plant_carousel` (
  `id` varchar(10) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `plant_name` varchar(255) DEFAULT NULL,
  `illustration_url` text DEFAULT NULL,
  `season` varchar(50) DEFAULT NULL,
  `planting_period` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `care_tips` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`care_tips`)),
  `event_details` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`event_details`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `plant_carousel`
--

INSERT INTO `plant_carousel` (`id`, `title`, `plant_name`, `illustration_url`, `season`, `planting_period`, `description`, `care_tips`, `event_details`) VALUES
('1', 'Étoile Violette du Jardin d\'Hiver', 'Purple Dome', 'https://images.ctfassets.net/b85ozb2q358o/956447963fed0a8f0e6f04c976aff20a3a6faacea348aee82a4e7186463344fd/cd46c17a7111d16c83282619fca62cc0/image.png', 'Hiver', 'Octobre à Décembre', 'Le Purple Dome est une variété d\'aster particulièrement adaptée à la saison hivernale. Ses fleurs violettes apportent une touche de couleur au jardin pendant les mois froids.', '[\"Arroser modérément en hiver\", \"Protéger du gel intense\", \"Tailler les tiges fanées\"]', '{\"title\": \"Atelier Hivernal : Cultiver l\'Aster Purple Dome\", \"workshopDate\": \"2024-12-15\", \"location\": \"Jardin des Plantes, Paris\", \"activities\": [\"Atelier de plantation\", \"Conseils d\'entretien hivernal\", \"Échange de boutures\"]}'),
('2', 'Messagère d\'hiver', 'Jonquille', 'https://images.ctfassets.net/b85ozb2q358o/a1d2779b3f0fe1988fc557b4fde4b95075f721f445fb7f61795d40c35dde2de8/3dfd28fd9493d177a3e8e2eab7d34e39/quand-comment-planter-bulbes-fleurs-2.jpg', 'Hiver', 'Septembre à Novembre', 'La jonquille est l\'un des premiers messagers du printemps. Plantée en hiver, elle fleurira dès les premiers jours du printemps, apportant couleur et espoir.', '[\"Planter les bulbes à 10-15cm de profondeur\", \"Espacer les bulbes de 10cm\", \"Arroser légèrement après la plantation\"]', '{\"title\": \"Les Secrets des Bulbes de Jonquilles\", \"workshopDate\": \"2025-01-20\", \"location\": \"Parc de Bagatelle, Paris\", \"activities\": [\"Démonstration de plantation de bulbes\", \"Préparation du sol\", \"Conseils de multiplication\"]}'),
('3', 'Parfum d\'Hiver Enchanteur', 'Jacinthe', 'https://images.ctfassets.net/b85ozb2q358o/95dd345e42affef5d6f6387dcde452fb1be0f9a51863a3fa605a023940ea62b9/9746b55f9623bf93850dffe214848276/quand-comment-planter-bulbes-fleurs-4.jpg', 'Hiver', 'Octobre à Décembre', 'La jacinthe est réputée pour son parfum envoûtant. C\'est une excellente plante pour égayer l\'intérieur pendant l\'hiver.', '[\"Planter dans un sol bien drainé\", \"Maintenir à une température fraîche\", \"Éviter l\'excès d\'eau\"]', '{\"title\": \"Atelier Jacinthes : Du Bulbe à la Fleur\", \"workshopDate\": \"2025-02-05\", \"location\": \"Jardin du Luxembourg, Paris\", \"activities\": [\"Culture en pot\", \"Forçage des bulbes\", \"Entretien hivernal\"]}'),
('4', 'Soleil d\'Or Hivernal', 'Jasmin jaune', 'https://media.istockphoto.com/id/1362665290/fr/photo/champ-de-colza-jaune-sur-fond-de-nature-ciel-bleu-fleurs-de-canola-en-fleurs-concept-de.jpg?s=612x612&w=0&k=20&c=K5Rw4dhreZIzSe95Akdkld5uhI27FCEn2cjEAvUbJVg=', 'Hiver', 'Novembre à Janvier', 'Le jasmin d\'hiver illumine les jardins de ses fleurs jaunes pendant la saison froide. Il est parfait pour les haies et les treillages.', '[\"Tailler après la floraison\", \"Protéger les jeunes plants du gel\", \"Pailler le pied en hiver\"]', '{\"title\": \"Maîtriser la Culture du Jasmin d\'Hiver\", \"workshopDate\": \"2024-12-10\", \"location\": \"Parc Monceau, Paris\", \"activities\": [\"Techniques de taille\", \"Installation de supports\", \"Protection hivernale\"]}'),
('5', 'Fleur de Givre Résistante', 'Bruyère', 'https://emova-monceaufleurs-fr-storage.omn.proximis.com/Imagestorage/images/2560/1600/5fb26ebf51a7e_bruyere_variete_callune.jpg', 'Hiver', 'Septembre à Mars', 'La bruyère est une plante rustique qui fleurit tout l\'hiver. Elle est idéale pour les massifs et les jardinières en période hivernale.', '[\"Planter en terre de bruyère\", \"Arroser régulièrement\", \"Tailler légèrement après floraison\"]', '{\"title\": \"Découverte de la Bruyère d\'Hiver\", \"workshopDate\": \"2025-01-15\", \"location\": \"Jardin des Serres d\'Auteuil, Paris\", \"activities\": [\"Création de massifs\", \"Composition de jardinières\", \"Entretien saisonnier\"]}');

-- --------------------------------------------------------

--
-- Structure de la table `recipes`
--

CREATE TABLE `recipes` (
  `id` varchar(10) NOT NULL,
  `name` varchar(255) NOT NULL,
  `image_url` text DEFAULT NULL,
  `category` varchar(50) DEFAULT NULL,
  `preparation_time` varchar(50) DEFAULT NULL,
  `difficulty` varchar(50) DEFAULT NULL,
  `servings` varchar(50) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `ingredients` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`ingredients`)),
  `instructions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`instructions`)),
  `benefits` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`benefits`)),
  `notes` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `recipes`
--

INSERT INTO `recipes` (`id`, `name`, `image_url`, `category`, `preparation_time`, `difficulty`, `servings`, `description`, `ingredients`, `instructions`, `benefits`, `notes`) VALUES
('1', 'Infusion Détox au Thym', 'https://www.creapharma.ch/wp-content/uploads/2021/09/AdobeStock_69434082-tisane-thym.jpeg', 'Bien-être', '10 min', 'Facile', '1 personne', 'Une infusion purifiante qui combine les propriétés détoxifiantes du thym avec la douceur du miel. Parfaite pour renforcer votre système immunitaire et apaiser les maux de gorge.', '[\"2 branches de thym frais\", \"1 cuillère à café de miel bio\", \"1 rondelle de citron bio\", \"25cl d\'eau minérale\"]', '[\"Faire bouillir l\'eau dans une casserole\", \"Ajouter les branches de thym frais\", \"Laisser infuser pendant 5-7 minutes\", \"Filtrer l\'infusion\", \"Ajouter le miel et la rondelle de citron\"]', '[\"Renforce le système immunitaire\", \"Propriétés antibactériennes\", \"Soulage les maux de gorge\", \"Facilite la digestion\"]', 'Pour un effet optimal, boire 2 à 3 tasses par jour. Éviter en cas d\'allergie au thym ou aux plantes de la famille des lamiacées.'),
('2', 'Masque Hydratant à l\'Aloe Vera', 'https://media.istockphoto.com/id/1345935119/fr/photo/feuilles-et-tranches-fra%C3%AEches-daloe-vera-ou-daloe-vera-sur-fond-blanc.jpg?s=612x612&w=0&k=20&c=3G29dhXbeDoa5lnkMpZ1PkUsnjwOH3uj5yh3c0XLXaM=', 'Beauté', '15 min', 'Moyen', '2-3 applications', 'Un masque naturel riche en vitamines qui hydrate en profondeur et apaise les peaux sensibles. L\'aloe vera, connu pour ses propriétés régénérantes, est combiné à des ingrédients nourrissants.', '[\"3 cuillères à soupe de gel d\'aloe vera\", \"1 cuillère à café de miel\", \"5 gouttes d\'huile essentielle de lavande\", \"1/2 avocat mûr\"]', '[\"Extraire la pulpe de l\'avocat et l\'écraser\", \"Mélanger avec le gel d\'aloe vera\", \"Ajouter le miel et l\'huile essentielle\", \"Bien homogénéiser le mélange\", \"Appliquer sur le visage pendant 15-20 minutes\", \"Rincer à l\'eau tiède\"]', '[\"Hydratation intense\", \"Apaise les irritations\", \"Effet anti-âge naturel\", \"Régénération cellulaire\"]', 'Conserver au réfrigérateur et utiliser dans les 48h. Faire un test cutané avant la première utilisation.'),
('3', 'Baume Relaxant Muscles et Articulations', 'https://img.passeportsante.net/1200x675/2018-04-03/i85582-huile-essentielle-lavande-fine.webp', 'Bien-être', '30 min', 'Expert', '100ml', 'Un baume apaisant qui combine les propriétés anti-inflammatoires de l\'arnica et des huiles essentielles pour soulager les douleurs musculaires et articulaires.', '[\"50ml d\'huile de coco bio\", \"30g de cire d\'abeille\", \"20g de poudre d\'arnica\", \"10 gouttes d\'HE de gaulthérie\", \"10 gouttes d\'HE de lavande\"]', '[\"Faire fondre l\'huile de coco au bain-marie\", \"Ajouter la cire d\'abeille et mélanger\", \"Incorporer la poudre d\'arnica\", \"Retirer du feu et laisser tiédir\", \"Ajouter les huiles essentielles\", \"Verser dans un pot hermétique\"]', '[\"Soulage les douleurs musculaires\", \"Réduit les inflammations\", \"Améliore la circulation\", \"Effet relaxant\"]', 'Ne pas appliquer sur une peau lésée. Éviter l\'exposition au soleil après application. Contre-indiqué chez la femme enceinte et allaitante.'),
('4', 'Tisane Apaisante du Soir', 'https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'Relaxation', '8 min', 'Facile', '1 personne', 'Une tisane relaxante qui combine les vertus apaisantes de la camomille, de la lavande et de la mélisse pour favoriser un sommeil réparateur.', '[\"1 cuillère à café de fleurs de camomille\", \"1 cuillère à café de fleurs de lavande\", \"1 cuillère à café de feuilles de mélisse\", \"1 cuillère à café de miel de tilleul\", \"25cl d\'eau\"]', '[\"Porter l\'eau à ébullition\", \"Mettre les plantes dans une boule à thé\", \"Verser l\'eau chaude sur les plantes\", \"Laisser infuser 5-7 minutes\", \"Ajouter le miel selon le goût\"]', '[\"Favorise l\'endormissement\", \"Réduit l\'anxiété\", \"Améliore la qualité du sommeil\", \"Effet relaxant naturel\"]', 'À consommer 30 minutes avant le coucher. Ne pas dépasser 2 tasses par jour. Déconseillé aux personnes sensibles à la camomille.'),
('5', 'Smoothie Énergie au Curcuma', 'https://static.wixstatic.com/media/931e46_8e9de5d03de148ab8344c5962654d00e~mv2.jpg/v1/fill/w_600,h_764,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/931e46_8e9de5d03de148ab8344c5962654d00e~mv2.jpg', 'Santé', '5 min', 'Facile', '2 personnes', 'Un smoothie revitalisant, riche en antioxydants et en curcuma pour renforcer vos défenses naturelles.', '[\"1 banane mûre\", \"1/2 cuillère à café de curcuma en poudre\", \"200ml de lait d\'amande\", \"1 cuillère à café de graines de chia\", \"1 cuillère à café de miel (optionnel)\"]', '[\"Mixer tous les ingrédients jusqu\'à obtenir une texture lisse.\", \"Servir frais dans des verres.\", \"Décorer avec quelques graines de chia.\"]', '[\"Améliore l\'immunité\", \"Réduit l\'inflammation\", \"Apporte de l\'énergie\", \"Effet détoxifiant\"]', 'À consommer le matin pour un boost d\'énergie. Ajuster la quantité de curcuma si le goût est trop prononcé.'),
('6', 'Gommage Corps au Café', 'https://media.istockphoto.com/id/1136853764/fr/photo/ingr%C3%A9dients-naturels-pour-le-corps-fait-maison-chocolat-caf%C3%A9-sucre-gommage-au-sel.jpg?s=612x612&w=0&k=20&c=A5LA7SmCAWesqCyzEpky19ys0BRgNujUEcOTeAvN1Bc=', 'Beauté', '10 min', 'Facile', '1 application', 'Un gommage maison revitalisant, parfait pour exfolier la peau et réduire l\'apparence de la cellulite.', '[\"3 cuillères à soupe de marc de café\", \"2 cuillères à soupe d\'huile de coco\", \"1 cuillère à soupe de sucre roux\"]', '[\"Mélanger tous les ingrédients jusqu\'à obtenir une pâte.\", \"Appliquer sur la peau humide en massant doucement.\", \"Rincer à l\'eau tiède.\"]', '[\"Exfolie en douceur\", \"Stimule la circulation sanguine\", \"Lisse la peau\", \"Réduit la cellulite\"]', 'À utiliser une fois par semaine. Ne pas utiliser sur une peau irritée ou sensible.'),
('7', 'Huile Relaxante à l\'Eucalyptus', 'https://www.plantes-et-sante.fr/images/istock-1222477682.jpg_720_1000_2', 'Relaxation', '15 min', 'Moyen', '50ml', 'Une huile apaisante idéale pour les massages et pour réduire le stress grâce aux bienfaits de l\'eucalyptus.', '[\"40ml d\'huile d\'amande douce\", \"10 gouttes d\'huile essentielle d\'eucalyptus\", \"5 gouttes d\'huile essentielle de lavande\"]', '[\"Mélanger les huiles essentielles à l\'huile d\'amande douce.\", \"Conserver dans un flacon hermétique.\", \"Utiliser pour masser les zones tendues.\"]', '[\"Apaise les tensions\", \"Favorise la relaxation\", \"Hydrate la peau\", \"Effet rafraîchissant\"]', 'Éviter tout contact avec les yeux. Ne pas utiliser chez les enfants ou les femmes enceintes.');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `plants`
--
ALTER TABLE `plants`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `plant_carousel`
--
ALTER TABLE `plant_carousel`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `recipes`
--
ALTER TABLE `recipes`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
